### ISSUE TITLE
Adding download link for downloading/installing Beet in case it's not installed

### ISSUE THREAD

**Issue by ioBanker** [BTS-CM/NFT.next.js#5]
When user doesn't have Beet installed, the below error will appear, I suggest to add downloading/installing Beet link in popup error.

Could not connect to Beet
Unable to connect to Beet on port 60555. Please launch Beet or install it.
Install Beet here: https://github.com/bitshares/beet/releases/latest

**Comment by grctest** [comment]
Added a button to download beet within the error prompt, thanks for reporting the issue 👍
